import { isValidSequenceNumber } from '../number';

describe('number utils', () => {
    describe('isValidSequenceNumber', () => {
        test.each([
            ['1st', true],
            ['2nd', true],
            ['3rd', true],
            ['4th', true],
            ['5th', true],
            ['6th', true],
            ['7th', true],
            ['8th', true],
            ['9th', true],
            ['10th', true],
            ['11th', true],
            ['111th', true],
            ['12th', true],
            ['112th', true],
            ['13th', true],
            ['113th', true],
            ['14th', true],
            ['114th', true],
            ['15th', true],
            ['115th', true],
            ['16th', true],
            ['116th', true],
            ['17th', true],
            ['117th', true],
            ['18th', true],
            ['118th', true],
            ['19th', true],
            ['119th', true],
            ['20th', true],
            ['21st', true],
            ['221st', true],
            ['22nd', true],
            ['23rd', true],
            ['24th', true],
            ['25th', true],
            ['26th', true],
            ['27th', true],
            ['28th', true],
            ['29th', true],
            ['30th', true],
            ['31st', true],
            ['21rd', false],
            ['37nd', false],
            ['rd', false],
            ['st', false],
            ['nd', false],
            ['hello', false],
            ['not a number', false],
            ['0', false],
        ])(
            '%p is a valid sequence number input - %p',
            (input: string, expected: boolean) => {
                expect(isValidSequenceNumber(input)).toBe(expected);
            },
        );
    });
});
