# This workflow will do a release deployment on a semver tag push via "npm version"
# For more information see https://docs.npmjs.com/cli/version

name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Matches all semantic versioning tags

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}

        # Execute script in the deployment user's
        # home dir to keep commands env-dependent.
        script: |
          ~/loot-lord.sh
